twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        nom_du_site: "Aventure d'Axel dans le Livre des Cinq Anneaux"

when@test:
    twig:
        strict_variables: true
